config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  root 'sessions#login'

  # localhost:3000/sessions/login
  # get 'sessions/login'
  # post 'sessions/create'
  # get 'sessions/logout'

  # localhost:3000/login
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#logout'

  get '/auth/github', as: 'github'
  get '/auth/github/callback', to:'sessions#github'

  # get '/users/new'
  # get '/signup'
  # get 'users/create'
  # post '/users' => 'users#create' #, as: 'create_user'
  # get '/users/:id', to: 'users#show'

  # get '/users/:id/houses', to: 'houses#index'
  resources :houses #,only: || except: [:index, :show] 
  
  resources :users, only: [:show, :new, :create] do 
    resources :houses, only: [:show, :new, :index] # :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# house_url => http://localhost:3000/houses
# house_path => /houses

# controller#actions
# # houses_controller
# **houses#
# ^ show => '/houses/:id' => GET => house_path(house_obj)
# index => '/houses' => GET => houses_path
# create => '/houses' => POST => houses_path
# new => '/houses/new' => GET => new_house_path
# ^ edit => '/houses/:id/edit' => GET => edit_house_path(house_obj)
# ^ update => '/houses/:id' => PATCH / PUT => house_path(house_obj)
# ^ destory => '/houses/:id' => DELETE => house_path(house_obj)

# HTTP VERBs:

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
  belongs_to :user
  has_many :rooms, dependent: :destroy

  validates :location, :size, presence: true
  # accepts_nested_attributes_for :rooms

  # room_params = {
  #   0: {:name, :theme, :use},
  #   1: {:name, :theme, :use}
  # }

  # room_params.values = [
  #   {:name, :theme, :use}.
  #   {:name, :theme, :use}
  # ]

  def rooms_attributes=(room_params)
    room_params.values.each do |room_attrs| # {"name"=>"Main", "theme"=>"Choas", "use"=>"1"}
      unless room_attrs.values.any?(&:empty?)
        # if !(room_attrs.values.any?(&:empty?))
        # binding.pry
        # new_room = Room.new(room_attrs)
        # self.rooms << new_room
        self.rooms << Room.new(room_attrs)
      end
    end 
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :house

  validates :name, :theme, presence: true

  # accepts_nested_attributes_for :house

  def house_attributes=(house_params)
    # binding.pry
    
    unless house_params[:location].empty? || house_params[:size].empty?
      self.house = House.new(
        location: house_params[:location],
        size: house_params[:size]
      )
    end
  
    #     self.house = House.new(house_params)
    #   end
    # end 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :houses

  validates :email, presence: true, unless: :uid
  has_secure_password

  def display_userName
    self.username.capitalize if self.username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # private 
  # def current_user
  #   @current_user ||= User.find_by_id(session[:user_id])
  # end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
before_action :get_house, only: [:show, :edit, :update, :destroy]
# before_action :is_logged?, except: [:index, :show]

  def index
    # binding.pry
    if params.include?('user_id') #|| !!params[:user_id] || params[:user_id]
      # current_user = user
      # @houses = user.houses
      # @houses = current_user.houses
      @houses = User.find_by_id(params[:user_id]).houses
    else
      @houses = House.all
    end
    # render :'folder/file_name'
  end

  def show
    # binding.pry
    if params.include?('user_id') #|| !!params[:user_id] || params[:user_id]
      # current_user = user
      # @houses = user.houses
      @houses = current_user.houses
      # @house = User.find_by_id(params[:user_id]).houses.find_by_id(params[:id])
    end
  # @house = get_house
  end

  def new
    # binding.pry
    @house = House.new
    @house.rooms.build
    @house.rooms.build

    # @rooms = Room.new
    # if params.include?('user_id')
    #   # @house = User.find_by_id(params[:user_id]).houses.new
    #   @house = User.find_by_id(params[:user_id]).houses.build
    # else
      # @house = House.new
      # @house.rooms.build
      # @house.rooms.build
      # @house.rooms.build
      # @house.rooms.build
      # @house.rooms.build
      # @rooms = [Room.new, Room.new]
    # end
    # @all_users = User.all
  end

  def create
    @new_house = current_user.houses.build(house_params)
    # binding.pry

    if @new_house.save
      redirect_to house_path(@new_house)
    else
      # @all_users = User.all
     render :new
    end
  end

  def edit
    if current_user.houses.include?(@house) 
      @all_users = User.all
      render :edit
    else
      redirect_to houses_path
    end
  end

  def update
  # @house = get_house
   if @house.update(house_params)
     redirect_to house_path(@house)
   else
     @all_users = User.all
    render :edit
   end

    @all_users = User.all
  end

  def destroy
    @house.destroy if current_user.houses.include?(@house) 
    redirect_to houses_path
  end

  private
    def house_params # selecting house attrs from params
      #params => {
      # auth_token: 123232,
      # house: {location: 'str', size: #, user_id: #, house_type: ''}
      # }
      params.require(:house).permit(
        :location, 
        :size, 
        rooms_attributes: [
          :name, 
          :theme, 
          :use
        ],
        third_hash: [
          :attr1,
          :attr2
        ]
      )
    end

    def get_house # finding house in table from params
      @house = House.find_by_id(params[:id])
      # House.find(params[:id])
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
    @room.build_house
    @houses = current_user.houses
  end

  def create
    @new_room = Room.new(room_params)
    @new_room.house.user = current_user unless @new_room.house.user
    # @new_room.house.user = current_user if !(@room.house)
    binding.pry
    @new_room.save!
    redirect_to house_path(@new_room.house)
  end

  def destroy
    room = Room.find_by_id(params[:id])
    past_house = room.house

    room.destroy
    redirect_to house_path(past_house)
  end

  private

  def room_params
    params.require(:room).permit(:name, :theme, :use, :house_id, house_attributes: [:location, :size, :user_id]
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def create
    @user = User.find_by(email: session_params[:email])
    binding.pry

    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to houses_path
    else
      # redirect_to login_path
      render :login
    end
  end

  def logout
    session.clear
    redirect_to login_path
  end

  def github
    # binding.pry

    user = User.find_or_create_by(uid: github_params['uid']) do |u|
      u.username = github_params['info']['name'] || github_params['info']['nickname']
      u.email = github_params['info']['email']
      u.password = github_params['credentials']['token']
    end
 
    session[:user_id] = user.id
 
    redirect_to houses_path
  end

  private
  def session_params
    params.require('session').permit(:email, :password)
  end

  def github_params
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @new_user = User.new(email: params[:email], password: params[:password])

    if @new_user.save # @new_user.valid
      # add session info

      # _path #=> '/houses'
      # _url #=> 'http://localhost:3000/houses'
      redirect_to houses_path
    else
      render :new
    end
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/houses/_form.html.erb
Location: <%= form_field.text_field :location, {class: 'test_class'} %><br/>

  Size: <%= form_field.number_field :size, required: true %><br/>

app/views/houses/edit.html.erb
<% @house = @house || @new_house %>
<% if @house.errors.any? %>
  <%= render 'layouts/error', {obj: @house} %>
<% end %>


<h1>Add Your House here</h1>
<%= form_for(@house) do |f| %>
  <%= render 'form', {form_field: f} %><br/>
  <%= f.submit %>
<% end %>

app/views/houses/index.html.erb
<h1>List of Current User Houses</h1>

<ul>
  <% @houses.each.with_index(1) do |h_obj, idx| %>
    <li><%= idx%>. Location: <%= link_to h_obj.location, house_path(h_obj) %> 
    <br/> Owner: <%= h_obj.user.email %> </li>
    <br/>
  <% end %>
</ul>

app/views/houses/new.html.erb
<% @house = @house || @new_house %>
<% if @house.errors.any? %>
  <%= render 'layouts/error', {obj: @house} %>
<% end %>


<h1>Add Your House here</h1>
<%= form_for(@house) do |f| %>
  <%= render 'form', {form_field: f} %>
  
  <h4> Add Room Info here: </h4>
  <%= f.fields_for :rooms do |room_form| %>
    <%= room_form.label :name %>
    <%= room_form.text_field :name %> <br/>
    <%= room_form.label :theme %>
    <%= room_form.text_field :theme %> <br/>
    <%= room_form.label "in_use" %>
    <%= room_form.check_box :use %> <br/><br/>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/houses/new_formTag.html.erb
<h1>Add Your House here</h1>
<%= form_tag(houses_path) do %>
  <%#= form_tag('/users')%>
  Location: <%= text_field_tag 'house[location]', nil, {class: 'test_class'} %><br/>
  Size: <%= number_field_tag 'house[size]'%><br/>

  Select the owner: <%= select_tag 'house[user_id]', !options_from_collection_for_select(@all_users, :id, :email), include_blank: true %><br/>
  <%= hidden_field_tag 'house[secret]'%>
  <%= submit_tag("Create House")%>
<% end %>

app/views/houses/show.html.erb
House Location: <%= @house.location %><br/>
House size: <%= @house.size %><br/>
Current Rooms:
<ol>
  <% @house.rooms.each do |room| %>
   <%= render 'rooms/room_list', {room_obj: room}%><br/>
</ol>
Owner: <%= @house.user.email %><br/>
<% end %>
<%= link_to 'Edit', edit_house_path(@house) %> | 
<%= link_to 'Delete', house_path(@house), method: :delete %>

app/views/layouts/_error.html.erb
<div id="error_explanation">
    <h2>
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this house from being saved:
    </h2>
 
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %> 
    </ul>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RhouseLog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if session.has_key?(:user_id) %>
      <b>Welcome <%= current_user.display_userName || 'Person' %></b>
      <%= link_to 'LogOut', logout_path, method: :delete %>
      <%= link_to 'Add House', new_house_path %><br/><br/><br/>
    <% else %>
      <%= link_to 'LogIn', login_path%>
      <%= link_to 'LogIn with GitHub', github_path %>
      <%= link_to 'SignUp', new_user_path %><br/><br/><br/>

    <% end%>

    <%= yield %>
  </body>
</html>

app/views/rooms/_room_list.html.erb
 <li> <%= room_obj.house.location %> house <%= room_obj.name %> <br/>
    For additional info click: <%= link_to 'here', room_path(room_obj) %> 
    </li

app/views/rooms/index.html.erb
<h1>List of Rooms Houses</h1>

<ol>
  <% @rooms.each do |r_obj| %>
   <%= render 'room_list', {room_obj: r_obj}%><br/>
  <% end %>
</ol>

app/views/rooms/new.html.erb
<h1> Add a Room Here </h1>

<%= form_for @room do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br/>
  <%= f.label :theme %>
  <%= f.text_field :theme %> <br/>
  <%= f.label "in_use" %>
  <%= f.check_box :use %> <br/>
  <p>Add House Info Below</p>
  <%= f.fields_for :house do |h_form| %>
    Location: <%= h_form.text_field :location%><br/>
   Size:  <%= h_form.number_field :size%><br/>
   <%= h_form.hidden_field :user_id %>
  <% end %>
  </p> Select a House </p>
                      <!--  #params key  #el 4 iteration #display 2 user #parmas val -->
  <%= f.collection_select :house_id, @houses, :id, :location, prompt: true %><br/><br/>
<%#= f.collection_check_boxes :house_id, @houses, :id, :location, prompt: true %>
<%= f.submit %>
  
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Welcome, SignUp Here</h1>
<%= form_tag(users_path) do %>
  <%#= form_tag('/users')%>
  Email: <%= text_field_tag 'email' %><br/>
  Password: <%= password_field_tag 'password'%><br/>
  <%= submit_tag("Create User")%>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>